# Generated by Django 5.0.3 on 2024-04-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company_id',
            new_name='companyId',
        ),
    ]
